import './globals.css';
import { Inter } from 'next/font/google';
import HeaderWrapper from '../components/HeaderWrapper';
import FooterWrapper from '../components/FooterWrapper';

// Configure the Inter font
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
  description:
    'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
  keywords: [
    'drones UK',
    'UK drone laws',
    'drone reviews',
    'beginner drones',
    'flying drones',
    'drone safety',
    'CAA drone code',
    'NozuDrones',
  ],
  authors: [{ name: 'The Nozu Team' }],
  creator: 'The Nozu Team',
  publisher: 'NozuDrones.co.uk',
  openGraph: {
    title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
    description:
      'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
    url: 'https://www.nozudrones.co.uk',
    siteName: 'NozuDrones.co.uk',
    images: [
      {
        url: 'https://www.nozudrones.co.uk/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'NozuDrones Website Banner',
      },
    ],
    locale: 'en_GB',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
    description:
      'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
    creator: '@NozuDrones',
    images: ['https://www.nozudrones.co.uk/twitter-image.jpg'],
  },
  alternates: {
    canonical: 'https://www.nozudrones.co.uk',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicons generated by RealFaviconGenerator.net and custom 16x16 */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#333333" />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        <HeaderWrapper />
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
