import './globals.css';
import { Inter } from 'next/font/google';
import HeaderWrapper from '../components/HeaderWrapper';
import FooterWrapper from '../components/FooterWrapper';

// Configure the Inter font
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Define a CSS variable for the font
  display: 'swap', // Optimize font loading
});

export const metadata = {
  title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
  description: 'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
  keywords: ['drones UK', 'UK drone laws', 'drone reviews', 'beginner drones', 'flying drones', 'drone safety', 'CAA drone code', 'NozuDrones'],
  authors: [{ name: 'The Nozu Team' }],
  creator: 'The Nozu Team',
  publisher: 'NozuDrones.co.uk',
  // Open Graph / Facebook
  openGraph: {
    title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
    description: 'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
    url: 'https://www.nozudrones.co.uk',
    siteName: 'NozuDrones.co.uk',
    images: [
      {
        url: 'https://www.nozudrones.co.uk/og-image.jpg', // Replace with your actual OG image
        width: 1200,
        height: 630,
        alt: 'NozuDrones Website Banner',
      },
    ],
    locale: 'en_GB',
    type: 'website',
  },
  // Twitter
  twitter: {
    card: 'summary_large_image',
    title: 'NozuDrones.co.uk - Your UK Drone Journey Starts Here',
    description: 'Unbiased drone reviews, comprehensive UK drone laws, and essential flying tips for beginners and enthusiasts. Become an EEAT-certified drone expert with NozuDrones.',
    creator: '@NozuDrones', // Replace with your actual Twitter handle
    images: ['https://www.nozudrones.co.uk/twitter-image.jpg'], // Replace with your actual Twitter image
  },
  // Canonical URL
  alternates: {
    canonical: 'https://www.nozudrones.co.uk',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicons generated by RealFaviconGenerator.net and custom 16x16 */}
        {/* SVG Favicon (Modern Browsers - Full Logo) */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/* Apple Touch Icon (iOS devices) */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        {/* Android Chrome / PWA icons */}
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png" />
        {/* Standard Favicon (Fallback for older browsers) */}
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        {/* Favicon for older browsers */}
        <link rel="shortcut icon" href="/favicon.ico" />
        {/* Web App Manifest for PWA */}
        <link rel="manifest" href="/site.webmanifest" />
        {/* Theme color for Android Chrome */}
        <meta name="theme-color" content="#333333" />
      </head>
      <body className={`${inter.variable} font-sans antialiased min-h-screen flex flex-col`}> {/* Added min-h-screen flex flex-col */}
        <HeaderWrapper />
        <main className="flex-grow"> {/* Ensure main content area grows to push footer down */}
          {children}
        </main>
        <FooterWrapper />
      </body>
    </html>
  );
}