import './globals.css';
import { Geist, Geist_Mono } from "next/font/google";
import HeaderWrapper from '../components/HeaderWrapper.jsx'; // Updated import path
import FooterWrapper from '../components/FooterWrapper.jsx'; // Updated import path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // Updated title and description for NozuDrones
  title: "NozuDrones - Your UK Drone Companion",
  description: "Unlock the world of drones with in-depth reviews, up-to-date UK drone laws, and essential flying tips. Become an EEAT-certified drone expert with NozuDrones.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicons generated by RealFaviconGenerator.net and custom 16x16 */}
        {/* SVG Favicon (Modern Browsers - Full Logo) */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />

        {/* Apple Touch Icon (iOS "Add to Home Screen" - Full Logo with background) */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

        {/* Android Chrome / PWA Icons (Full Logo) */}
        <link rel="icon" type="image/png" sizes="192x192" href="/web-app-manifest-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/web-app-manifest-512x512.png" />

        {/* Standard/Legacy Favicons (PNGs - 32x32 is Full Logo, 16x16 is Empty Bubble) */}
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" /> {/* This is your specialized empty bubble icon */}

        {/* Microsoft Tile Icons (if RFG generated mstile-144x144.png) */}
        <meta name="msapplication-TileColor" content="#ffffff" /> {/* Adjust to your brand's primary color if different */}
        <meta name="msapplication-TileImage" content="/mstile-144x144.png" />

        {/* Theme Color for Browsers (e.g., Android Chrome address bar) */}
        <meta name="theme-color" content="#ffffff" /> {/* Adjust to your brand's primary color */}

        {/* Web App Manifest (for PWAs) */}
        <link rel="manifest" href="/site.webmanifest" />

        {/* Fallback .ico (contains multiple sizes, usually 16x16, 32x32) */}
        <link rel="shortcut icon" href="/favicon.ico" />

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Main Container: Overall layout, background fallback, and font styling */}
        <div className="relative min-h-screen font-sans antialiased bg-nozu-sky-blue text-nozu-dark-grey">

          {/* Content Wrapper: This div now handles its own scrolling and contains the header, main, and footer */}
          <div className="relative z-10 flex flex-col h-screen overflow-y-auto">

            {/* Header is now a separate Client Component */}
            <HeaderWrapper />

            {/* This is where the page content (children) will be rendered */}
            {children}

            {/* Section Delineation: Pure White border (added before footer) */}
            <div className="w-full h-4 bg-white"></div> {/* Reduced height to h-4 (16px) */}

            {/* Footer is now a separate Server Component */}
            <FooterWrapper />
          </div>
        </div>
      </body>
    </html>
  );
}
